version: "3.9"
services:
  server:
    build:
      context: ./apps/server
    env_file:
      - ./apps/server/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build:
      context: ./apps/client
    env_file:
      - ./apps/client/.env
    ports:
      - "3000:3000"
    depends_on:
      - server
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: